const axios = require('axios');
const { Pool } = require('pg');

// Constants
const CLIENT_ID = '1000.4SMTI5UB88N1HHQ37IB14Z8FUSXK2M';
const CLIENT_SECRET = '4c14a5eb4e3b0643c0a515864d05e21def40aad09d';
const REFRESH_TOKEN = '1000.91e0505679d2e67f49d2a592178e57cc.9d679633039bfbc2f90eb84225270590';
const API_BASE_URL = 'https://www.zohoapis.in/books/v3';
const TOKEN_REFRESH_URL = 'https://accounts.zoho.in/oauth/v2/token';

// Database connection
const pool = new Pool({
    host: 'tec-ext-db.clymeiomojq1.ap-southeast-1.rds.amazonaws.com',
    database: 'postgres',
    user: 'postgres',
    password: 'T5hHf2CvhTW4fpT1cmJ9', // Replace with actual password
    port: 5432,
});

let accessToken = null; // To store the current access token

// Function to refresh the access token
async function refreshAccessToken() {
    try {
        const response = await axios.post(TOKEN_REFRESH_URL, null, {
            params: {
                refresh_token: REFRESH_TOKEN,
                client_id: CLIENT_ID,
                client_secret: CLIENT_SECRET,
                grant_type: 'refresh_token',
            },
        });
        accessToken = response.data.access_token;
    } catch (error) {
        console.error('Error refreshing access token:', error.response?.data || error.message);
        throw error;
    }
}

// Function to fetch invoice details from Zoho Books
async function fetchInvoiceDetails(invoiceId) {
    try {
        const response = await axios.get(`${API_BASE_URL}/invoices/${invoiceId}`, {
            headers: {
                Authorization: `Zoho-oauthtoken ${accessToken}`,
            },
        });
        return response.data;
    } catch (error) {
        if (error.response?.status === 401) {
            console.log('Access token expired. Refreshing token...');
            await refreshAccessToken();
            return fetchInvoiceDetails(invoiceId); // Retry after refreshing token
        }

        if (error.response?.status === 429) {
            console.log('Rate limit reached. Stopping script. Resume tomorrow.');
            process.exit(1); // This will stop the script immediately
        }

        console.error('Error fetching invoice details:', error.response?.data || error.message);
        throw error;
    }
}

// Function to ensure the invoice_detail table exists
async function ensureTableExists(client) {
    const createTableQuery = `
    CREATE TABLE IF NOT EXISTS zoho_books.invoice_detail (
      invoice_id VARCHAR(255) PRIMARY KEY,
      date VARCHAR,
      type VARCHAR,
      email VARCHAR,
      notes VARCHAR,
      taxes JSONB,
      terms VARCHAR,
      total NUMERIC,
      gst_no VARCHAR,
      status VARCHAR,
      balance NUMERIC,
      contact JSONB,
      discount NUMERIC,
      due_date VARCHAR,
      bcy_total NUMERIC,
      documents JSONB,
      ewaybills JSONB,
      sub_total NUMERIC,
      tax_total NUMERIC,
      adjustment NUMERIC,
      color_code VARCHAR,
      is_emailed BOOLEAN,
      is_pre_gst BOOLEAN,
      is_taxable BOOLEAN,
      line_items JSONB,
      page_width VARCHAR,
      tax_reg_no VARCHAR,
      approver_id VARCHAR,
      currency_id VARCHAR,
      customer_id VARCHAR,
      debit_notes JSONB,
      estimate_id VARCHAR,
      invoice_url VARCHAR,
      merchant_id VARCHAR,
      orientation VARCHAR,
      page_height VARCHAR,
      salesorders JSONB,
      template_id VARCHAR,
      created_date VARCHAR,
      created_time TIMESTAMP,
      is_backorder VARCHAR,
      lock_details JSONB,
      no_of_copies NUMERIC,
      payment_made NUMERIC,
      sub_statuses JSONB,
      submitted_by VARCHAR,
      submitter_id VARCHAR,
      tax_rounding VARCHAR,
      ach_supported BOOLEAN,
      bcy_sub_total NUMERIC,
      bcy_tax_total NUMERIC,
      created_by_id VARCHAR,
      currency_code VARCHAR,
      custom_fields JSONB,
      customer_name VARCHAR,
      discount_type VARCHAR,
      exchange_rate NUMERIC,
      gst_treatment VARCHAR,
      merchant_name VARCHAR,
      payment_terms NUMERIC,
      sales_channel VARCHAR,
      salesorder_id VARCHAR,
      schedule_time VARCHAR,
      tax_treatment VARCHAR,
      template_name VARCHAR,
      template_type VARCHAR,
      approvers_list JSONB,
      bcy_adjustment NUMERIC,
      discount_total NUMERIC,
      invoice_number VARCHAR,
      invoice_source VARCHAR,
      reminders_sent NUMERIC,
      roundoff_value NUMERIC,
      salesperson_id VARCHAR,
      shipping_bills JSONB,
      submitted_date VARCHAR,
      attachment_name VARCHAR,
      billing_address JSONB,
      contact_persons JSONB,
      created_by_name VARCHAR,
      credits_applied NUMERIC,
      currency_symbol VARCHAR,
      merchant_gst_no VARCHAR,
      payment_options JSONB,
      place_of_supply VARCHAR,
      price_precision NUMERIC,
      shipping_charge NUMERIC,
      subject_content VARCHAR,
      can_send_in_mail BOOLEAN,
      computation_type VARCHAR,
      contact_category VARCHAR,
      deliverychallans JSONB,
      discount_percent NUMERIC,
      is_inclusive_tax BOOLEAN,
      payment_discount NUMERIC,
      reference_number VARCHAR,
      salesperson_name VARCHAR,
      shipping_address JSONB,
      write_off_amount NUMERIC,
      custom_field_hash JSONB,
      ecomm_operator_id VARCHAR,
      last_payment_date VARCHAR,
      reference_invoice JSONB,
      salesorder_number VARCHAR,
      show_no_of_copies BOOLEAN,
      submitted_by_name VARCHAR,
      tax_specification VARCHAR,
      zcrm_potential_id VARCHAR,
      bcy_discount_total NUMERIC,
      client_viewed_time VARCHAR,
      current_sub_status VARCHAR,
      gst_return_details JSONB,
      last_modified_time VARCHAR,
      submitted_by_email VARCHAR,
      bcy_shipping_charge NUMERIC,
      ecomm_operator_name VARCHAR,
      is_autobill_enabled BOOLEAN,
      is_viewed_by_client BOOLEAN,
      last_modified_by_id VARCHAR,
      payment_terms_label VARCHAR,
      shipping_charge_tax VARCHAR,
      tax_amount_withheld NUMERIC,
      zcrm_potential_name VARCHAR,
      can_send_invoice_sms BOOLEAN,
      recurring_invoice_id VARCHAR,
      tds_calculation_type VARCHAR,
      ach_payment_initiated BOOLEAN,
      current_sub_status_id VARCHAR,
      dispatch_from_address JSONB,
      ecomm_operator_gst_no VARCHAR,
      is_eway_bill_required BOOLEAN,
      payment_expected_date VARCHAR,
      reason_for_debit_note VARCHAR,
      adjustment_description VARCHAR,
      allow_partial_payments BOOLEAN,
      customer_custom_fields JSONB,
      filed_in_vat_return_id VARCHAR,
      is_discount_before_tax BOOLEAN,
      reference_invoice_type VARCHAR,
      shipping_charge_tax_id VARCHAR,
      submitted_by_photo_url VARCHAR,
      bcy_shipping_charge_tax VARCHAR,
      contact_persons_details JSONB,
      currency_name_formatted VARCHAR,
      last_reminder_sent_date VARCHAR,
      filed_in_vat_return_name VARCHAR,
      filed_in_vat_return_type VARCHAR,
      payment_reminder_enabled BOOLEAN,
      reverse_charge_tax_total NUMERIC,
      shipping_charge_sac_code VARCHAR,
      shipping_charge_tax_name VARCHAR,
      shipping_charge_tax_type VARCHAR,
      unused_retainer_payments NUMERIC,
      transaction_rounding_type VARCHAR,
      customer_custom_field_hash JSONB,
      discount_applied_on_amount NUMERIC,
      sub_total_inclusive_of_tax NUMERIC,
      suspended_recurring_invoice VARCHAR,
      next_reminder_date_formatted VARCHAR,
      inprocess_transaction_present BOOLEAN,
      shipping_charge_tax_formatted VARCHAR,
      includes_package_tracking_info BOOLEAN,
      offline_created_date_with_time VARCHAR,
      shipping_charge_tax_percentage VARCHAR,
      can_generate_ewaybill_using_irn BOOLEAN,
      customer_default_billing_address JSONB,
      reader_offline_payment_initiated BOOLEAN,
      shipping_charge_exclusive_of_tax NUMERIC,
      shipping_charge_inclusive_of_tax NUMERIC,
      shipping_charge_tax_exemption_id VARCHAR,
      is_client_review_settings_enabled BOOLEAN,
      shipping_charge_tax_exemption_code VARCHAR,
      stop_reminder_until_payment_expected_date BOOLEAN,
      shipping_charge_exclusive_of_tax_formatted VARCHAR,
      shipping_charge_inclusive_of_tax_formatted VARCHAR
    );
  `;
    await client.query(createTableQuery);
}

async function getLatestSyncTime(client) {
    const result = await client.query(`
        SELECT MAX(created_time) as last_sync
        FROM zoho_books.invoice_detail
    `);
    return result.rows[0].last_sync;
}

// Function to process and sync data
async function syncInvoices() {
    const client = await pool.connect();
    try {
        // Ensure the invoice_detail table exists
        await ensureTableExists(client);

        const lastSyncTime = await getLatestSyncTime(client);
        console.log(`Last sync time: ${lastSyncTime}`);

        // Fetch all invoices (no last sync time for the first run)
        const invoiceQuery = `
      SELECT invoice_id, created_time 
      FROM zoho_books.invoices where created_time > $1
      ORDER BY created_time ASC`;

        const { rows: invoices } = await client.query(invoiceQuery, [lastSyncTime]);

        console.log(`${invoices.length} invoices to sync.`);

        for (const invoice of invoices) {
            const { invoice_id, created_time } = invoice;

            // Fetch invoice details
            const details = await fetchInvoiceDetails(invoice_id);

            console.log(details.invoice?.date, "invoice details");

            // Insert details into invoice_detail table
            // const values = [
            //     invoice_id,
            //     details.invoice?.date || null,
            //     details.invoice?.type || null,
            //     details.invoice?.email || null,
            //     details.invoice?.notes || null,
            //     details.invoice?.taxes || null,
            //     details.invoice?.terms || null,
            //     details.invoice?.total || null,
            //     details.invoice?.gst_no || null,
            //     details.invoice?.status || null,

            //     details.invoice?.balance || null,
            //     details.invoice?.contact || null,
            //     details.invoice?.discount || null,
            //     details.invoice?.due_date || null,
            //     details.invoice?.bcy_total || null,
            //     details.invoice?.documents || null,
            //     details.invoice?.ewaybills || null,

            //     details.invoice?.sub_total || null,
            //     details.invoice?.tax_total || null,
            //     details.invoice?.adjustment || null,
            //     details.invoice?.color_code || null,
            //     details.invoice?.is_emailed || null,
            //     details.invoice?.is_pre_gst || null,

            //     details.invoice?.is_taxable || null,
            //     details.invoice?.line_items || null,
            //     details.invoice?.page_width || null,
            //     details.invoice?.tax_reg_no || null,
            //     details.invoice?.approver_id || null,
            //     details.invoice?.currency_id || null,

            //     details.invoice?.customer_id || null,
            //     details.invoice?.debit_notes || null,
            //     details.invoice?.estimate_id || null,
            //     details.invoice?.invoice_url || null,
            //     details.invoice?.merchant_id || null,
            //     details.invoice?.orientation || null,

            //     details.invoice?.page_height || null,
            //     details.invoice?.salesorders || null,
            //     details.invoice?.template_id || null,
            //     details.invoice?.created_date || null,
            //     created_time,
            //     details.invoice?.is_backorder || null,
            //     details.invoice?.lock_details || null,
            //     details.invoice?.no_of_copies || null,
            //     details.invoice?.payment_made || null,
            //     details.invoice?.sub_statuses || null,

            //     details.invoice?.submitted_by || null,
            //     details.invoice?.submitter_id || null,
            //     details.invoice?.tax_rounding || null,
            //     details.invoice?.ach_supported || null,
            //     details.invoice?.bcy_sub_total || null,

            //     details.invoice?.bcy_tax_total || null,
            //     details.invoice?.created_by_id || null,
            //     details.invoice?.currency_code || null,
            //     details.invoice?.custom_fields || null,
            //     details.invoice?.customer_name || null,

            //     details.invoice?.discount_type || null,
            //     details.invoice?.exchange_rate || null,
            //     details.invoice?.gst_treatment || null,
            //     details.invoice?.merchant_name || null,
            //     details.invoice?.payment_terms || null,

            //     details.invoice?.sales_channel || null,
            //     details.invoice?.salesorder_id || null,
            //     details.invoice?.schedule_time || null,
            //     details.invoice?.tax_treatment || null,
            //     details.invoice?.template_name || null,

            //     details.invoice?.template_type || null,
            //     details.invoice?.approvers_list || null,
            //     details.invoice?.bcy_adjustment || null,
            //     details.invoice?.discount_total || null,
            //     details.invoice?.invoice_number || null,

            //     details.invoice?.invoice_source || null,
            //     details.invoice?.reminders_sent || null,
            //     details.invoice?.roundoff_value || null,
            //     details.invoice?.salesperson_id || null,
            //     details.invoice?.shipping_bills || null,

            //     details.invoice?.submitted_date || null,
            //     details.invoice?.attachment_name || null,
            //     details.invoice?.billing_address || null,
            //     details.invoice?.contact_persons || null,
            //     details.invoice?.created_by_name || null,
            //     details.invoice?.credits_applied || null,
            //     details.invoice?.currency_symbol || null,
            //     details.invoice?.merchant_gst_no || null,
            //     details.invoice?.payment_options || null,
            //     details.invoice?.place_of_supply || null,
            //     details.invoice?.price_precision || null,
            //     details.invoice?.shipping_charge || null,
            //     details.invoice?.subject_content || null,
            //     details.invoice?.can_send_in_mail || null,
            //     details.invoice?.computation_type || null,
            //     details.invoice?.contact_category || null,
            //     details.invoice?.deliverychallans || null,
            //     details.invoice?.discount_percent || null,
            //     details.invoice?.is_inclusive_tax || null,
            //     details.invoice?.payment_discount || null,
            //     details.invoice?.reference_number || null,
            //     details.invoice?.salesperson_name || null,
            //     details.invoice?.shipping_address || null,
            //     details.invoice?.write_off_amount || null,
            //     details.invoice?.custom_field_hash || null,
            //     details.invoice?.ecomm_operator_id || null,
            //     details.invoice?.last_payment_date || null,
            //     details.invoice?.reference_invoice || null,
            //     details.invoice?.salesorder_number || null,
            //     details.invoice?.show_no_of_copies || null,
            //     details.invoice?.submitted_by_name || null,
            //     details.invoice?.tax_specification || null,
            //     details.invoice?.zcrm_potential_id || null,
            //     details.invoice?.bcy_discount_total || null,
            //     details.invoice?.client_viewed_time || null,
            //     details.invoice?.current_sub_status || null,
            //     details.invoice?.gst_return_details || null,
            //     details.invoice?.last_modified_time || null,
            //     details.invoice?.submitted_by_email || null,
            //     details.invoice?.bcy_shipping_charge || null,
            //     details.invoice?.ecomm_operator_name || null,
            //     details.invoice?.is_autobill_enabled || null,
            //     details.invoice?.is_viewed_by_client || null,
            //     details.invoice?.last_modified_by_id || null,
            //     details.invoice?.payment_terms_label || null,
            //     details.invoice?.shipping_charge_tax || null,
            //     details.invoice?.tax_amount_withheld || null,
            //     details.invoice?.zcrm_potential_name || null,
            //     details.invoice?.can_send_invoice_sms || null,
            //     details.invoice?.recurring_invoice_id || null,
            //     details.invoice?.tds_calculation_type || null,
            //     details.invoice?.ach_payment_initiated || null,
            //     details.invoice?.current_sub_status_id || null,
            //     details.invoice?.dispatch_from_address || null,
            //     details.invoice?.ecomm_operator_gst_no || null,
            //     details.invoice?.is_eway_bill_required || null,
            //     details.invoice?.payment_expected_date || null,
            //     details.invoice?.reason_for_debit_note || null,
            //     details.invoice?.adjustment_description || null,
            //     details.invoice?.allow_partial_payments || null,
            //     details.invoice?.customer_custom_fields || null,
            //     details.invoice?.filed_in_vat_return_id || null,
            //     details.invoice?.is_discount_before_tax || null,
            //     details.invoice?.reference_invoice_type || null,
            //     details.invoice?.shipping_charge_tax_id || null,
            //     details.invoice?.submitted_by_photo_url || null,
            //     details.invoice?.bcy_shipping_charge_tax || null,
            //     details.invoice?.contact_persons_details || null,
            //     details.invoice?.currency_name_formatted || null,
            //     details.invoice?.last_reminder_sent_date || null,
            //     details.invoice?.filed_in_vat_return_name || null,
            //     details.invoice?.filed_in_vat_return_type || null,
            //     details.invoice?.payment_reminder_enabled || null,
            //     details.invoice?.reverse_charge_tax_total || null,
            //     details.invoice?.shipping_charge_sac_code || null,
            //     details.invoice?.shipping_charge_tax_name || null,
            //     details.invoice?.shipping_charge_tax_type || null,
            //     details.invoice?.unused_retainer_payments || null,
            //     details.invoice?.transaction_rounding_type || null,
            //     details.invoice?.customer_custom_field_hash || null,
            //     details.invoice?.discount_applied_on_amount || null,
            //     details.invoice?.sub_total_inclusive_of_tax || null,
            //     details.invoice?.suspended_recurring_invoice || null,
            //     details.invoice?.next_reminder_date_formatted || null,
            //     details.invoice?.inprocess_transaction_present || null,
            //     details.invoice?.shipping_charge_tax_formatted || null,
            //     details.invoice?.includes_package_tracking_info || null,
            //     details.invoice?.offline_created_date_with_time || null,
            //     details.invoice?.shipping_charge_tax_percentage || null,
            //     details.invoice?.can_generate_ewaybill_using_irn || null,
            //     details.invoice?.customer_default_billing_address || null,
            //     details.invoice?.reader_offline_payment_initiated || null,
            //     details.invoice?.shipping_charge_exclusive_of_tax || null,
            //     details.invoice?.shipping_charge_inclusive_of_tax || null,
            //     details.invoice?.shipping_charge_tax_exemption_id || null,
            //     details.invoice?.is_client_review_settings_enabled || null,
            //     details.invoice?.shipping_charge_tax_exemption_code || null,
            //     details.invoice?.stop_reminder_until_payment_expected_date || null,
            //     details.invoice?.shipping_charge_exclusive_of_tax_formatted || null,
            //     details.invoice?.shipping_charge_inclusive_of_tax_formatted || null
            // ];

            const values = [
                invoice_id,
                details.invoice?.date || null,
                details.invoice?.type || null,
                details.invoice?.email || null,
                details.invoice?.notes || null,
                details.invoice?.taxes ? JSON.stringify(details.invoice.taxes) : null,
                details.invoice?.terms || null,
                details.invoice?.total || null,
                details.invoice?.gst_no || null,
                details.invoice?.status || null,
                details.invoice?.balance || null,
                details.invoice?.contact ? JSON.stringify(details.invoice.contact) : null,
                details.invoice?.discount || null,
                details.invoice?.due_date || null,
                details.invoice?.bcy_total || null,
                details.invoice?.documents ? JSON.stringify(details.invoice.documents) : null,
                details.invoice?.ewaybills ? JSON.stringify(details.invoice.ewaybills) : null,
                details.invoice?.sub_total || null,
                details.invoice?.tax_total || null,
                details.invoice?.adjustment || null,
                details.invoice?.color_code || null,
                details.invoice?.is_emailed || null,
                details.invoice?.is_pre_gst || null,
                details.invoice?.is_taxable || null,
                details.invoice?.line_items ? JSON.stringify(details.invoice.line_items) : null,
                details.invoice?.page_width || null,
                details.invoice?.tax_reg_no || null,
                details.invoice?.approver_id || null,
                details.invoice?.currency_id || null,
                details.invoice?.customer_id || null,
                details.invoice?.debit_notes ? JSON.stringify(details.invoice.debit_notes) : null,
                details.invoice?.estimate_id || null,
                details.invoice?.invoice_url || null,
                details.invoice?.merchant_id || null,
                details.invoice?.orientation || null,
                details.invoice?.page_height || null,
                details.invoice?.salesorders ? JSON.stringify(details.invoice.salesorders) : null,
                details.invoice?.template_id || null,
                details.invoice?.created_date || null,
                created_time,
                details.invoice?.is_backorder || null,
                details.invoice?.lock_details ? JSON.stringify(details.invoice.lock_details) : null,
                details.invoice?.no_of_copies || null,
                details.invoice?.payment_made || null,
                details.invoice?.sub_statuses ? JSON.stringify(details.invoice.sub_statuses) : null,
                details.invoice?.submitted_by || null,
                details.invoice?.submitter_id || null,
                details.invoice?.tax_rounding || null,
                details.invoice?.ach_supported || null,
                details.invoice?.bcy_sub_total || null,
                details.invoice?.bcy_tax_total || null,
                details.invoice?.created_by_id || null,
                details.invoice?.currency_code || null,
                details.invoice?.custom_fields ? JSON.stringify(details.invoice.custom_fields) : null,
                details.invoice?.customer_name || null,
                details.invoice?.discount_type || null,
                details.invoice?.exchange_rate || null,
                details.invoice?.gst_treatment || null,
                details.invoice?.merchant_name || null,
                details.invoice?.payment_terms || null,
                details.invoice?.sales_channel || null,
                details.invoice?.salesorder_id || null,
                details.invoice?.schedule_time || null,
                details.invoice?.tax_treatment || null,
                details.invoice?.template_name || null,
                details.invoice?.template_type || null,
                details.invoice?.approvers_list ? JSON.stringify(details.invoice.approvers_list) : null,
                details.invoice?.bcy_adjustment || null,
                details.invoice?.discount_total || null,
                details.invoice?.invoice_number || null,
                details.invoice?.invoice_source || null,
                details.invoice?.reminders_sent || null,
                details.invoice?.roundoff_value || null,
                details.invoice?.salesperson_id || null,
                details.invoice?.shipping_bills ? JSON.stringify(details.invoice.shipping_bills) : null,
                details.invoice?.submitted_date || null,
                details.invoice?.attachment_name || null,
                details.invoice?.billing_address ? JSON.stringify(details.invoice.billing_address) : null,
                details.invoice?.contact_persons ? JSON.stringify(details.invoice.contact_persons) : null,
                details.invoice?.created_by_name || null,
                details.invoice?.credits_applied || null,
                details.invoice?.currency_symbol || null,
                details.invoice?.merchant_gst_no || null,
                details.invoice?.payment_options ? JSON.stringify(details.invoice.payment_options) : null,
                details.invoice?.place_of_supply || null,
                details.invoice?.price_precision || null,
                details.invoice?.shipping_charge || null,
                details.invoice?.subject_content || null,
                details.invoice?.can_send_in_mail || null,
                details.invoice?.computation_type || null,
                details.invoice?.contact_category || null,
                details.invoice?.deliverychallans ? JSON.stringify(details.invoice.deliverychallans) : null,
                details.invoice?.discount_percent || null,
                details.invoice?.is_inclusive_tax || null,
                details.invoice?.payment_discount || null,
                details.invoice?.reference_number || null,
                details.invoice?.salesperson_name || null,
                details.invoice?.shipping_address ? JSON.stringify(details.invoice.shipping_address) : null,
                details.invoice?.write_off_amount || null,
                details.invoice?.custom_field_hash ? JSON.stringify(details.invoice.custom_field_hash) : null,
                details.invoice?.ecomm_operator_id || null,
                details.invoice?.last_payment_date || null,
                details.invoice?.reference_invoice ? JSON.stringify(details.invoice.reference_invoice) : null,
                details.invoice?.salesorder_number || null,
                details.invoice?.show_no_of_copies || null,
                details.invoice?.submitted_by_name || null,
                details.invoice?.tax_specification || null,
                details.invoice?.zcrm_potential_id || null,
                details.invoice?.bcy_discount_total || null,
                details.invoice?.client_viewed_time || null,
                details.invoice?.current_sub_status || null,
                details.invoice?.gst_return_details ? JSON.stringify(details.invoice.gst_return_details) : null,
                details.invoice?.last_modified_time || null,
                details.invoice?.submitted_by_email || null,
                details.invoice?.bcy_shipping_charge || null,
                details.invoice?.ecomm_operator_name || null,
                details.invoice?.is_autobill_enabled || null,
                details.invoice?.is_viewed_by_client || null,
                details.invoice?.last_modified_by_id || null,
                details.invoice?.payment_terms_label || null,
                details.invoice?.shipping_charge_tax || null,
                details.invoice?.tax_amount_withheld || null,
                details.invoice?.zcrm_potential_name || null,
                details.invoice?.can_send_invoice_sms || null,
                details.invoice?.recurring_invoice_id || null,
                details.invoice?.tds_calculation_type || null,
                details.invoice?.ach_payment_initiated || null,
                details.invoice?.current_sub_status_id || null,
                details.invoice?.dispatch_from_address ? JSON.stringify(details.invoice.dispatch_from_address) : null,
                details.invoice?.ecomm_operator_gst_no || null,
                details.invoice?.is_eway_bill_required || null,
                details.invoice?.payment_expected_date || null,
                details.invoice?.reason_for_debit_note || null,
                details.invoice?.adjustment_description || null,
                details.invoice?.allow_partial_payments || null,
                details.invoice?.customer_custom_fields ? JSON.stringify(details.invoice.customer_custom_fields) : null,
                details.invoice?.filed_in_vat_return_id || null,
                details.invoice?.is_discount_before_tax || null,
                details.invoice?.reference_invoice_type || null,
                details.invoice?.shipping_charge_tax_id || null,
                details.invoice?.submitted_by_photo_url || null,
                details.invoice?.bcy_shipping_charge_tax || null,
                details.invoice?.contact_persons_details ? JSON.stringify(details.invoice.contact_persons_details) : null,
                details.invoice?.currency_name_formatted || null,
                details.invoice?.last_reminder_sent_date || null,
                details.invoice?.filed_in_vat_return_name || null,
                details.invoice?.filed_in_vat_return_type || null,
                details.invoice?.payment_reminder_enabled || null,
                details.invoice?.reverse_charge_tax_total || null,
                details.invoice?.shipping_charge_sac_code || null,
                details.invoice?.shipping_charge_tax_name || null,
                details.invoice?.shipping_charge_tax_type || null,
                details.invoice?.unused_retainer_payments || null,
                details.invoice?.transaction_rounding_type || null,
                details.invoice?.customer_custom_field_hash ? JSON.stringify(details.invoice.customer_custom_field_hash) : null,
                details.invoice?.discount_applied_on_amount || null,
                details.invoice?.sub_total_inclusive_of_tax || null,
                details.invoice?.suspended_recurring_invoice || null,
                details.invoice?.next_reminder_date_formatted || null,
                details.invoice?.inprocess_transaction_present || null,
                details.invoice?.shipping_charge_tax_formatted || null,
                details.invoice?.includes_package_tracking_info || null,
                details.invoice?.offline_created_date_with_time || null,
                details.invoice?.shipping_charge_tax_percentage || null,
                details.invoice?.can_generate_ewaybill_using_irn || null,
                details.invoice?.customer_default_billing_address ? JSON.stringify(details.invoice.customer_default_billing_address) : null,
                details.invoice?.reader_offline_payment_initiated || null,
                details.invoice?.shipping_charge_exclusive_of_tax || null,
                details.invoice?.shipping_charge_inclusive_of_tax || null,
                details.invoice?.shipping_charge_tax_exemption_id || null,
                details.invoice?.is_client_review_settings_enabled || null,
                details.invoice?.shipping_charge_tax_exemption_code || null,
                details.invoice?.stop_reminder_until_payment_expected_date || null,
                details.invoice?.shipping_charge_exclusive_of_tax_formatted || null,
                details.invoice?.shipping_charge_inclusive_of_tax_formatted || null
            ];




            await client.query(
                `INSERT INTO zoho_books.invoice_detail (
                invoice_id, date, type, email, notes, taxes, terms, total, gst_no, status,
                balance, contact, discount, due_date, bcy_total, documents, ewaybills,
                sub_total, tax_total, adjustment, color_code, is_emailed, is_pre_gst,
                is_taxable, line_items, page_width, tax_reg_no, approver_id, currency_id,
                customer_id, debit_notes, estimate_id, invoice_url, merchant_id, orientation,
                page_height, salesorders, template_id, created_date, created_time,
                is_backorder, lock_details, no_of_copies, payment_made, sub_statuses,
                submitted_by, submitter_id, tax_rounding, ach_supported, bcy_sub_total,
                bcy_tax_total, created_by_id, currency_code, custom_fields, customer_name,
                discount_type, exchange_rate, gst_treatment, merchant_name, payment_terms,
                sales_channel, salesorder_id, schedule_time, tax_treatment, template_name,
                template_type, approvers_list, bcy_adjustment, discount_total, invoice_number,
                invoice_source, reminders_sent, roundoff_value, salesperson_id, shipping_bills,
                submitted_date, attachment_name, billing_address, contact_persons,
                created_by_name, credits_applied, currency_symbol, merchant_gst_no,
                payment_options, place_of_supply, price_precision, shipping_charge,
                subject_content, can_send_in_mail, computation_type, contact_category,
                deliverychallans, discount_percent, is_inclusive_tax, payment_discount,
                reference_number, salesperson_name, shipping_address, write_off_amount,
                custom_field_hash, ecomm_operator_id, last_payment_date, reference_invoice,
                salesorder_number, show_no_of_copies, submitted_by_name, tax_specification,
                zcrm_potential_id, bcy_discount_total, client_viewed_time, current_sub_status,
                gst_return_details, last_modified_time, submitted_by_email, bcy_shipping_charge,
                ecomm_operator_name, is_autobill_enabled, is_viewed_by_client,
                last_modified_by_id, payment_terms_label, shipping_charge_tax,
                tax_amount_withheld, zcrm_potential_name, can_send_invoice_sms,
                recurring_invoice_id, tds_calculation_type, ach_payment_initiated,
                current_sub_status_id, dispatch_from_address, ecomm_operator_gst_no,
                is_eway_bill_required, payment_expected_date, reason_for_debit_note,
                adjustment_description, allow_partial_payments, customer_custom_fields,
                filed_in_vat_return_id, is_discount_before_tax, reference_invoice_type,
                shipping_charge_tax_id, submitted_by_photo_url, bcy_shipping_charge_tax,
                contact_persons_details, currency_name_formatted, last_reminder_sent_date,
                filed_in_vat_return_name, filed_in_vat_return_type, payment_reminder_enabled,
                reverse_charge_tax_total, shipping_charge_sac_code, shipping_charge_tax_name,
                shipping_charge_tax_type, unused_retainer_payments, transaction_rounding_type,
                customer_custom_field_hash, discount_applied_on_amount,
                sub_total_inclusive_of_tax, suspended_recurring_invoice,
                next_reminder_date_formatted, inprocess_transaction_present,
                shipping_charge_tax_formatted, includes_package_tracking_info,
                offline_created_date_with_time, shipping_charge_tax_percentage,
                can_generate_ewaybill_using_irn, customer_default_billing_address,
                reader_offline_payment_initiated, shipping_charge_exclusive_of_tax,
                shipping_charge_inclusive_of_tax, shipping_charge_tax_exemption_id,
                is_client_review_settings_enabled, shipping_charge_tax_exemption_code,
                stop_reminder_until_payment_expected_date,
                shipping_charge_exclusive_of_tax_formatted,
                shipping_charge_inclusive_of_tax_formatted
            ) 
            VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
                $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
                $21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
                $31, $32, $33, $34, $35, $36, $37, $38, $39, $40,
                $41, $42, $43, $44, $45, $46, $47, $48, $49, $50,
                $51, $52, $53, $54, $55, $56, $57, $58, $59, $60,
                $61, $62, $63, $64, $65, $66, $67, $68, $69, $70,
                $71, $72, $73, $74, $75, $76, $77, $78, $79, $80,
                $81, $82, $83, $84, $85, $86, $87, $88, $89, $90,
                $91, $92, $93, $94, $95, $96, $97, $98, $99, $100,
                $101, $102, $103, $104, $105, $106, $107, $108, $109, $110,
                $111, $112, $113, $114, $115, $116, $117, $118, $119, $120,
                $121, $122, $123, $124, $125, $126, $127, $128, $129, $130,
                $131, $132, $133, $134, $135, $136, $137, $138, $139, $140,
                $141, $142, $143, $144, $145, $146, $147, $148, $149, $150,
                $151, $152, $153, $154, $155, $156, $157, $158, $159, $160,
                $161, $162, $163, $164, $165, $166, $167, $168, $169, $170,
                $171, $172, $173, $174, $175
            )
            ON CONFLICT (invoice_id) DO UPDATE SET
                date = EXCLUDED.date,
                type = EXCLUDED.type,
                email = EXCLUDED.email,
                notes = EXCLUDED.notes,
                taxes = EXCLUDED.taxes,
                terms = EXCLUDED.terms,
                total = EXCLUDED.total,
                gst_no = EXCLUDED.gst_no,
                status = EXCLUDED.status,
                balance = EXCLUDED.balance,
                contact = EXCLUDED.contact,
                discount = EXCLUDED.discount,
                due_date = EXCLUDED.due_date,
                bcy_total = EXCLUDED.bcy_total,
                documents = EXCLUDED.documents,
                ewaybills = EXCLUDED.ewaybills,
                sub_total = EXCLUDED.sub_total,
                tax_total = EXCLUDED.tax_total,
                adjustment = EXCLUDED.adjustment,
                color_code = EXCLUDED.color_code,
                is_emailed = EXCLUDED.is_emailed,
                is_pre_gst = EXCLUDED.is_pre_gst,
                is_taxable = EXCLUDED.is_taxable,
                line_items = EXCLUDED.line_items,
                page_width = EXCLUDED.page_width,
                tax_reg_no = EXCLUDED.tax_reg_no,
                approver_id = EXCLUDED.approver_id,
                currency_id = EXCLUDED.currency_id,
                customer_id = EXCLUDED.customer_id,
                debit_notes = EXCLUDED.debit_notes,
                estimate_id = EXCLUDED.estimate_id,
                invoice_url = EXCLUDED.invoice_url,
                merchant_id = EXCLUDED.merchant_id,
                orientation = EXCLUDED.orientation,
                page_height = EXCLUDED.page_height,
                salesorders = EXCLUDED.salesorders,
                template_id = EXCLUDED.template_id,
                created_date = EXCLUDED.created_date,
                created_time = EXCLUDED.created_time,
                is_backorder = EXCLUDED.is_backorder,
                lock_details = EXCLUDED.lock_details,
                no_of_copies = EXCLUDED.no_of_copies,
                payment_made = EXCLUDED.payment_made,
                sub_statuses = EXCLUDED.sub_statuses,
                submitted_by = EXCLUDED.submitted_by,
                submitter_id = EXCLUDED.submitter_id,
                tax_rounding = EXCLUDED.tax_rounding,
                ach_supported = EXCLUDED.ach_supported,
                bcy_sub_total = EXCLUDED.bcy_sub_total,
                bcy_tax_total = EXCLUDED.bcy_tax_total,
                created_by_id = EXCLUDED.created_by_id,
                currency_code = EXCLUDED.currency_code,
                custom_fields = EXCLUDED.custom_fields,
                customer_name = EXCLUDED.customer_name,
                discount_type = EXCLUDED.discount_type,
                exchange_rate = EXCLUDED.exchange_rate,
                gst_treatment = EXCLUDED.gst_treatment,
                merchant_name = EXCLUDED.merchant_name,
                payment_terms = EXCLUDED.payment_terms,
                sales_channel = EXCLUDED.sales_channel,
                salesorder_id = EXCLUDED.salesorder_id,
                schedule_time = EXCLUDED.schedule_time,
                tax_treatment = EXCLUDED.tax_treatment,
                template_name = EXCLUDED.template_name,
                template_type = EXCLUDED.template_type,
                approvers_list = EXCLUDED.approvers_list,
                bcy_adjustment = EXCLUDED.bcy_adjustment,
                discount_total = EXCLUDED.discount_total,
                invoice_number = EXCLUDED.invoice_number,
                invoice_source = EXCLUDED.invoice_source,
                reminders_sent = EXCLUDED.reminders_sent,
                roundoff_value = EXCLUDED.roundoff_value,
                salesperson_id = EXCLUDED.salesperson_id,
                shipping_bills = EXCLUDED.shipping_bills,
                submitted_date = EXCLUDED.submitted_date,
                attachment_name = EXCLUDED.attachment_name,
                billing_address = EXCLUDED.billing_address,
                contact_persons = EXCLUDED.contact_persons,
                created_by_name = EXCLUDED.created_by_name,
                credits_applied = EXCLUDED.credits_applied,
                currency_symbol = EXCLUDED.currency_symbol,
                merchant_gst_no = EXCLUDED.merchant_gst_no,
                payment_options = EXCLUDED.payment_options,
                place_of_supply = EXCLUDED.place_of_supply,
                price_precision = EXCLUDED.price_precision,
                shipping_charge = EXCLUDED.shipping_charge,
                subject_content = EXCLUDED.subject_content,
                can_send_in_mail = EXCLUDED.can_send_in_mail,
                computation_type = EXCLUDED.computation_type,
                contact_category = EXCLUDED.contact_category,
                deliverychallans = EXCLUDED.deliverychallans,
                discount_percent = EXCLUDED.discount_percent,
                is_inclusive_tax = EXCLUDED.is_inclusive_tax,
                payment_discount = EXCLUDED.payment_discount,
                reference_number = EXCLUDED.reference_number,
                salesperson_name = EXCLUDED.salesperson_name,
                shipping_address = EXCLUDED.shipping_address,
                write_off_amount = EXCLUDED.write_off_amount,
                custom_field_hash = EXCLUDED.custom_field_hash,
                ecomm_operator_id = EXCLUDED.ecomm_operator_id,
                last_payment_date = EXCLUDED.last_payment_date,
                reference_invoice = EXCLUDED.reference_invoice,
                salesorder_number = EXCLUDED.salesorder_number,
                show_no_of_copies = EXCLUDED.show_no_of_copies,
                submitted_by_name = EXCLUDED.submitted_by_name,
                tax_specification = EXCLUDED.tax_specification,
                zcrm_potential_id = EXCLUDED.zcrm_potential_id,
                bcy_discount_total = EXCLUDED.bcy_discount_total,
                client_viewed_time = EXCLUDED.client_viewed_time,
                current_sub_status = EXCLUDED.current_sub_status,
                gst_return_details = EXCLUDED.gst_return_details,
                last_modified_time = EXCLUDED.last_modified_time,
                submitted_by_email = EXCLUDED.submitted_by_email,
                bcy_shipping_charge = EXCLUDED.bcy_shipping_charge,
                ecomm_operator_name = EXCLUDED.ecomm_operator_name,
                is_autobill_enabled = EXCLUDED.is_autobill_enabled,
                is_viewed_by_client = EXCLUDED.is_viewed_by_client,
                last_modified_by_id = EXCLUDED.last_modified_by_id,
                payment_terms_label = EXCLUDED.payment_terms_label,
                shipping_charge_tax = EXCLUDED.shipping_charge_tax,
                tax_amount_withheld = EXCLUDED.tax_amount_withheld,
                zcrm_potential_name = EXCLUDED.zcrm_potential_name,
                can_send_invoice_sms = EXCLUDED.can_send_invoice_sms,
                recurring_invoice_id = EXCLUDED.recurring_invoice_id,
                tds_calculation_type = EXCLUDED.tds_calculation_type,
                ach_payment_initiated = EXCLUDED.ach_payment_initiated,
                current_sub_status_id = EXCLUDED.current_sub_status_id,
                dispatch_from_address = EXCLUDED.dispatch_from_address,
                ecomm_operator_gst_no = EXCLUDED.ecomm_operator_gst_no,
                is_eway_bill_required = EXCLUDED.is_eway_bill_required,
                payment_expected_date = EXCLUDED.payment_expected_date,
                reason_for_debit_note = EXCLUDED.reason_for_debit_note,
                adjustment_description = EXCLUDED.adjustment_description,
                allow_partial_payments = EXCLUDED.allow_partial_payments,
                customer_custom_fields = EXCLUDED.customer_custom_fields,
                filed_in_vat_return_id = EXCLUDED.filed_in_vat_return_id,
                is_discount_before_tax = EXCLUDED.is_discount_before_tax,
                reference_invoice_type = EXCLUDED.reference_invoice_type,
                shipping_charge_tax_id = EXCLUDED.shipping_charge_tax_id,
                submitted_by_photo_url = EXCLUDED.submitted_by_photo_url,
                bcy_shipping_charge_tax = EXCLUDED.bcy_shipping_charge_tax,
                contact_persons_details = EXCLUDED.contact_persons_details,
                currency_name_formatted = EXCLUDED.currency_name_formatted,
                last_reminder_sent_date = EXCLUDED.last_reminder_sent_date,
                filed_in_vat_return_name = EXCLUDED.filed_in_vat_return_name,
                filed_in_vat_return_type = EXCLUDED.filed_in_vat_return_type,
                payment_reminder_enabled = EXCLUDED.payment_reminder_enabled,
                reverse_charge_tax_total = EXCLUDED.reverse_charge_tax_total,
                shipping_charge_sac_code = EXCLUDED.shipping_charge_sac_code,
                shipping_charge_tax_name = EXCLUDED.shipping_charge_tax_name,
                shipping_charge_tax_type = EXCLUDED.shipping_charge_tax_type,
                unused_retainer_payments = EXCLUDED.unused_retainer_payments,
                transaction_rounding_type = EXCLUDED.transaction_rounding_type,
                customer_custom_field_hash = EXCLUDED.customer_custom_field_hash,
                discount_applied_on_amount = EXCLUDED.discount_applied_on_amount,
                sub_total_inclusive_of_tax = EXCLUDED.sub_total_inclusive_of_tax,
                suspended_recurring_invoice = EXCLUDED.suspended_recurring_invoice,
                next_reminder_date_formatted = EXCLUDED.next_reminder_date_formatted,
                inprocess_transaction_present = EXCLUDED.inprocess_transaction_present,
                shipping_charge_tax_formatted = EXCLUDED.shipping_charge_tax_formatted,
                includes_package_tracking_info = EXCLUDED.includes_package_tracking_info,
                offline_created_date_with_time = EXCLUDED.offline_created_date_with_time,
                shipping_charge_tax_percentage = EXCLUDED.shipping_charge_tax_percentage,
                can_generate_ewaybill_using_irn = EXCLUDED.can_generate_ewaybill_using_irn,
                customer_default_billing_address = EXCLUDED.customer_default_billing_address,
                reader_offline_payment_initiated = EXCLUDED.reader_offline_payment_initiated,
                shipping_charge_exclusive_of_tax = EXCLUDED.shipping_charge_exclusive_of_tax,
                shipping_charge_inclusive_of_tax = EXCLUDED.shipping_charge_inclusive_of_tax,
                shipping_charge_tax_exemption_id = EXCLUDED.shipping_charge_tax_exemption_id,
                is_client_review_settings_enabled = EXCLUDED.is_client_review_settings_enabled,
                shipping_charge_tax_exemption_code = EXCLUDED.shipping_charge_tax_exemption_code,
                stop_reminder_until_payment_expected_date = EXCLUDED.stop_reminder_until_payment_expected_date,
                shipping_charge_exclusive_of_tax_formatted = EXCLUDED.shipping_charge_exclusive_of_tax_formatted,
                shipping_charge_inclusive_of_tax_formatted = EXCLUDED.shipping_charge_inclusive_of_tax_formatted`,
                values
            );

            console.log(`Synced invoice ${invoice_id}`);

            // Respect rate limit
            await new Promise((resolve) => setTimeout(resolve, 1000)); // 3 seconds per request (20 requests/min)
        }

        console.log('Invoice sync completed.');
    } catch (error) {
        console.error('Error during invoice sync:', error);
    } finally {
        client.release();
    }
}

// Main script execution
(async () => {
    try {
        console.log('Refreshing access token...');
        await refreshAccessToken();

        console.log('Starting invoice sync...');
        await syncInvoices();
    } catch (error) {
        console.error('Script failed:', error.message);
    } finally {
        await pool.end();
    }
})();
